# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9971be03ecee2bc0eec2683a8fdc492e033804223f2c1fd2d920b0dc38ca426f5cce5fdc14a711e2ce65809eea1a88bae363880083229d37c08ac98302035fde

test:
  secret_key_base: 365c65a21d0861817a22f9f16bf68ee3cff33352cff85a6116664e5ff25c0480b61297e937048da3fb927127cfe681caf237ef6511f5b9dfc9f6d96fe5370019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
